/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/test2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_59.geometry} material={nodes.Object_59.material} />
          <mesh geometry={nodes.Object_60.geometry} material={nodes.Object_60.material} />
          <mesh geometry={nodes.Object_61.geometry} material={nodes.Object_61.material} />
          <mesh geometry={nodes.Object_62.geometry} material={nodes.Object_62.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_57.geometry} material={materials['Kling_RAL_7004_szignlszrke.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_380.geometry} material={materials['festk___vilgosszrke.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_398.geometry} material={materials['Material__2142148542.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_392.geometry} material={materials['Kling_RAL_7016_antracitszrke.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_394.geometry} material={materials['Fal_burkolat_recepci_2_fa.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_406.geometry} material={materials['veg___7E_zld.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_408.geometry} material={materials['Material__2142148545.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_396.geometry} material={materials['Material__2142148541.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_402.geometry} material={materials['Material__2142148543.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_410.geometry} material={materials['PEN_MATERIAL12.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_412.geometry} material={materials['veg___7A_srga.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_49.geometry} material={materials['Material__2142148389.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_51.geometry} material={materials['Material__2142148535.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_19.geometry} material={materials['veg___7C_bord_.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_21.geometry} material={materials['veg___7B_kk.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_23.geometry} material={materials['veg___7F_narancs.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_25.geometry} material={materials['veg___7D_vilgos_kk.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_390.geometry} material={materials['Material__2142148546.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_414.geometry} material={materials['Material__2142148547.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_386.geometry} material={materials['Material__2142148548.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_378.geometry} material={materials['Material__2142148551.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_400.geometry} material={materials['festk___bord.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_404.geometry} material={materials['Material__2142148544.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_366.geometry} material={materials['fm___kertshl.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_74.geometry} material={materials['veg_antracit.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_76.geometry} material={materials['veg_tejveg.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_72.geometry} material={materials['veg___bkanyl_7A_srga.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_68.geometry} material={materials['Material__2142148519.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_78.geometry} material={materials['veg___tltsz.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_388.geometry} material={materials['fm___rozsdamentes_acl.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_384.geometry} material={materials['Material__2142148550.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_382.geometry} material={materials['Material__2142148549.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_106.geometry} material={materials['Kling_RAL_7044_selyemszrke.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_102.geometry} material={materials['Material__2142148467.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_108.geometry} material={materials['Material__2142148450.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_364.geometry} material={materials['Egyb_fu_kopott.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_114.geometry} material={materials['Material__2142148453.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_116.geometry} material={materials['Egyb_fu.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_98.geometry} material={materials['Egyb_rkzld.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_88.geometry} material={materials['Kling_RAL_7034_srgsszrke.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_90.geometry} material={materials['fm___acl.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_92.geometry} material={materials['ko___carrarai_fehr_mrvny.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_94.geometry} material={materials['muanyag___laminlt.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_96.geometry} material={materials['Material__2142148454.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_374.geometry} material={materials['Color_RGB_001_089_254.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_376.geometry} material={materials['A_883__Westag___1_.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_370.geometry} material={materials['Color_RAL_6018.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_372.geometry} material={materials['A_828__Westag___1_.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_100.geometry} material={materials['Material__2142148471.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_124.geometry} material={nodes.Object_124.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_128.geometry} material={nodes.Object_128.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_132.geometry} material={nodes.Object_132.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_136.geometry} material={nodes.Object_136.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_140.geometry} material={nodes.Object_140.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_144.geometry} material={nodes.Object_144.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_148.geometry} material={nodes.Object_148.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_152.geometry} material={nodes.Object_152.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_156.geometry} material={nodes.Object_156.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_160.geometry} material={nodes.Object_160.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_164.geometry} material={nodes.Object_164.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_168.geometry} material={nodes.Object_168.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_172.geometry} material={nodes.Object_172.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_176.geometry} material={nodes.Object_176.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_180.geometry} material={nodes.Object_180.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_184.geometry} material={nodes.Object_184.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_188.geometry} material={nodes.Object_188.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_192.geometry} material={nodes.Object_192.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_196.geometry} material={nodes.Object_196.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_220.geometry} material={nodes.Object_220.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_224.geometry} material={nodes.Object_224.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_236.geometry} material={nodes.Object_236.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_240.geometry} material={nodes.Object_240.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_244.geometry} material={nodes.Object_244.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_248.geometry} material={nodes.Object_248.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_252.geometry} material={nodes.Object_252.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_256.geometry} material={nodes.Object_256.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_260.geometry} material={nodes.Object_260.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_264.geometry} material={nodes.Object_264.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_268.geometry} material={nodes.Object_268.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_272.geometry} material={nodes.Object_272.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_276.geometry} material={nodes.Object_276.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_280.geometry} material={nodes.Object_280.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_284.geometry} material={nodes.Object_284.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_288.geometry} material={nodes.Object_288.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_292.geometry} material={nodes.Object_292.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_296.geometry} material={nodes.Object_296.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_300.geometry} material={nodes.Object_300.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_304.geometry} material={nodes.Object_304.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_308.geometry} material={nodes.Object_308.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_312.geometry} material={nodes.Object_312.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_316.geometry} material={nodes.Object_316.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_320.geometry} material={nodes.Object_320.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_324.geometry} material={nodes.Object_324.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_328.geometry} material={nodes.Object_328.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_332.geometry} material={nodes.Object_332.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_336.geometry} material={nodes.Object_336.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_340.geometry} material={nodes.Object_340.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_344.geometry} material={nodes.Object_344.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_348.geometry} material={nodes.Object_348.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_352.geometry} material={nodes.Object_352.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_356.geometry} material={nodes.Object_356.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_360.geometry} material={nodes.Object_360.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_120.geometry} material={materials['Material__2142148448.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_80.geometry} material={materials['Material__2142148388.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_66.geometry} material={materials['Missing_Fm_cink.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_47.geometry} material={materials['Material__2142148344.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_362.geometry} material={nodes.Object_362.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_368.geometry} material={materials['Dszburkolat_2.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_112.geometry} material={materials['Material__2142148539.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_416.geometry} material={materials['wire_087225087.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_110.geometry} material={materials['Material__2142148452.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_39.geometry} material={nodes.Object_39.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} />
          <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
          <mesh geometry={nodes.Object_33.geometry} material={nodes.Object_33.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_29.geometry} material={materials['Material__2142148470.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_86.geometry} material={materials['Material__2142148386.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_37.geometry} material={materials['Chrome.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_41.geometry} material={nodes.Object_41.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_35.geometry} material={materials['Fm_cink.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_27.geometry} material={materials['Material__2142148365.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_43.geometry} material={materials['Material__2142148484.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_104.geometry} material={materials['Material__2142148449.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_45.geometry} material={materials['Fellet_fehr.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material__2142148387.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_6.geometry} material={materials['Fellet_kermia__mzas.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
          <mesh geometry={nodes.Object_8.geometry} material={materials['Material__2142148536.001']} />
          <mesh geometry={nodes.Object_3.geometry} material={nodes.Object_3.material} />
          <mesh geometry={nodes.Object_3_1.geometry} material={nodes.Object_3_1.material} />
          <mesh geometry={nodes.Object_3_2.geometry} material={nodes.Object_3_2.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_55.geometry} material={materials['lambert1.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_53.geometry} material={materials['Kling_RAL_9001_krmfehr.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_122.geometry} material={nodes.Object_122.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_126.geometry} material={nodes.Object_126.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_130.geometry} material={nodes.Object_130.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_134.geometry} material={nodes.Object_134.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_138.geometry} material={nodes.Object_138.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_142.geometry} material={nodes.Object_142.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_146.geometry} material={nodes.Object_146.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_150.geometry} material={nodes.Object_150.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_154.geometry} material={nodes.Object_154.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_158.geometry} material={nodes.Object_158.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_162.geometry} material={nodes.Object_162.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_166.geometry} material={nodes.Object_166.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_170.geometry} material={nodes.Object_170.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_174.geometry} material={nodes.Object_174.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_178.geometry} material={nodes.Object_178.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_182.geometry} material={nodes.Object_182.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_186.geometry} material={nodes.Object_186.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_190.geometry} material={nodes.Object_190.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_194.geometry} material={nodes.Object_194.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_202.geometry} material={nodes.Object_202.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_206.geometry} material={nodes.Object_206.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_210.geometry} material={nodes.Object_210.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_214.geometry} material={nodes.Object_214.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_218.geometry} material={nodes.Object_218.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_222.geometry} material={nodes.Object_222.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_226.geometry} material={nodes.Object_226.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_230.geometry} material={nodes.Object_230.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_234.geometry} material={nodes.Object_234.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_238.geometry} material={nodes.Object_238.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_242.geometry} material={nodes.Object_242.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_246.geometry} material={nodes.Object_246.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_250.geometry} material={nodes.Object_250.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_254.geometry} material={nodes.Object_254.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_258.geometry} material={nodes.Object_258.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_262.geometry} material={nodes.Object_262.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_266.geometry} material={nodes.Object_266.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_270.geometry} material={nodes.Object_270.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_274.geometry} material={nodes.Object_274.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_278.geometry} material={nodes.Object_278.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_282.geometry} material={nodes.Object_282.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_286.geometry} material={nodes.Object_286.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_290.geometry} material={nodes.Object_290.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_294.geometry} material={nodes.Object_294.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_298.geometry} material={nodes.Object_298.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_302.geometry} material={nodes.Object_302.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_306.geometry} material={nodes.Object_306.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_310.geometry} material={nodes.Object_310.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_314.geometry} material={nodes.Object_314.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_318.geometry} material={nodes.Object_318.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_322.geometry} material={nodes.Object_322.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_326.geometry} material={nodes.Object_326.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_330.geometry} material={nodes.Object_330.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_334.geometry} material={nodes.Object_334.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_338.geometry} material={nodes.Object_338.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_342.geometry} material={nodes.Object_342.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_346.geometry} material={nodes.Object_346.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_350.geometry} material={nodes.Object_350.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_354.geometry} material={nodes.Object_354.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_358.geometry} material={nodes.Object_358.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_82.geometry} material={materials['Material__2142148342.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_64.geometry} material={materials['Material__2142148340.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_118.geometry} material={materials['Material__2142148364.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_84.geometry} material={materials['Material__2142148341.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
          <mesh geometry={nodes.Object_5_1.geometry} material={nodes.Object_5_1.material} />
          <mesh geometry={nodes.Object_5_2.geometry} material={nodes.Object_5_2.material} />
          <mesh geometry={nodes.Object_13.geometry} material={nodes.Object_13.material} />
          <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
          <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_17.geometry} material={materials['A_223__Westag_.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_70.geometry} material={nodes.Object_70.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/test2.glb')
